import { mkdirSync, writeFileSync } from 'fs';
import { join, relative } from 'path';

export function generateRouteFile(
  projectRoot: string,
  routePath: string,
  functionFiles: string[],
): void {
  const routeDir = join(projectRoot, 'app', ...routePath.split('/').filter(Boolean));
  mkdirSync(routeDir, { recursive: true });

  const routeFilePath = join(routeDir, 'route.ts');
  const relativeToRoute = (absPath: string) => {
    const rel = relative(routeDir, absPath);
    return rel.replace(/\.(ts|js)$/, '');
  };

  const imports = functionFiles
    .map((f) => `import "${relativeToRoute(f)}";`)
    .join('\n');

  const content = `// AUTO-GENERATED BY @usepingback/next — do not edit
import { createRouteHandler } from "@usepingback/next/handler";
${imports}

export const POST = createRouteHandler();
`;

  writeFileSync(routeFilePath, content);
}
