import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join, relative } from 'path';
import { glob } from 'glob';
import { loadConfig } from './config';
import { registerFunctions } from './register';

export async function discoverFunctionFiles(
  projectRoot: string,
  pattern: string,
): Promise<string[]> {
  const files = await glob(pattern, { cwd: projectRoot, absolute: true });

  return files.filter((file) => {
    const content = readFileSync(file, 'utf-8');
    return content.includes('@pingback/next');
  });
}

export function generateRouteFile(
  projectRoot: string,
  routePath: string,
  functionFiles: string[],
): void {
  const routeDir = join(projectRoot, 'app', ...routePath.split('/').filter(Boolean));
  mkdirSync(routeDir, { recursive: true });

  const routeFilePath = join(routeDir, 'route.ts');
  const relativeToRoute = (absPath: string) => {
    const rel = relative(routeDir, absPath);
    return rel.replace(/\.(ts|js)$/, '');
  };

  const imports = functionFiles
    .map((f) => `import "${relativeToRoute(f)}";`)
    .join('\n');

  const content = `// AUTO-GENERATED BY @pingback/next — do not edit
import { createRouteHandler } from "@pingback/next/handler";
${imports}

export const POST = createRouteHandler();
`;

  writeFileSync(routeFilePath, content);
}

export function withPingback(nextConfig: any = {}): any {
  const originalWebpack = nextConfig.webpack;
  let buildPromise: Promise<void> | null = null;

  return {
    ...nextConfig,
    webpack(config: any, context: any) {
      if (context.isServer && !buildPromise) {
        buildPromise = runPingbackBuild(context.dir, !context.dev).catch((err: Error) => {
          console.error('[pingback] Build failed:', err.message);
        });

        // Add a plugin that waits for registration to finish before build completes
        config.plugins.push({
          apply(compiler: any) {
            compiler.hooks.afterEmit.tapPromise('PingbackRegistration', async () => {
              if (buildPromise) await buildPromise;
            });
          },
        });
      }

      if (originalWebpack) {
        return originalWebpack(config, context);
      }
      return config;
    },
  };
}

async function runPingbackBuild(projectRoot: string, shouldRegister = true): Promise<void> {
  const config = await loadConfig(projectRoot);
  const files = await discoverFunctionFiles(projectRoot, config.functionsDir);

  console.log(`[pingback] Found ${files.length} function file(s)`);

  generateRouteFile(projectRoot, config.routePath, files);
  console.log(`[pingback] Generated route handler at app${config.routePath}/route.ts`);

  const routeDir = `app${config.routePath}`;
  const gitignorePath = join(projectRoot, '.gitignore');
  if (existsSync(gitignorePath)) {
    const gitignore = readFileSync(gitignorePath, 'utf-8');
    if (!gitignore.includes(routeDir)) {
      console.warn(`[pingback] Warning: Add "${routeDir}" to your .gitignore — it's auto-generated.`);
    }
  }

  if (files.length > 0 && shouldRegister) {
    for (const file of files) {
      try { await import(file); } catch (err) {
        console.warn(`[pingback] Could not import ${file}: ${(err as Error).message}`);
      }
    }
    try {
      const result = await registerFunctions(config);
      console.log(`[pingback] Registered ${result.jobs.length} function(s) with platform`);
    } catch (err) {
      console.error(`[pingback] Registration failed: ${(err as Error).message}`);
    }
  }
}
