import { mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'fs';
import { join } from 'path';
import { generateRouteFile, discoverFunctionFiles } from '../src/plugin';

describe('plugin', () => {
  const tmpDir = join(__dirname, '__tmp_plugin_test__');

  beforeEach(() => {
    mkdirSync(tmpDir, { recursive: true });
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  describe('discoverFunctionFiles', () => {
    it('should find .ts files matching the glob pattern', async () => {
      const pingbackDir = join(tmpDir, 'lib', 'pingback');
      mkdirSync(pingbackDir, { recursive: true });
      writeFileSync(join(pingbackDir, 'emails.ts'), 'import { cron } from "@usepingback/next";');
      writeFileSync(join(pingbackDir, 'sync.ts'), 'import { task } from "@usepingback/next";');
      writeFileSync(join(pingbackDir, 'utils.ts'), 'export function helper() { return 1; }');

      const files = await discoverFunctionFiles(tmpDir, 'lib/pingback/**/*.{ts,js}');

      expect(files).toHaveLength(2);
      expect(files.map((f) => f.replace(tmpDir + '/', ''))).toEqual(
        expect.arrayContaining(['lib/pingback/emails.ts', 'lib/pingback/sync.ts']),
      );
    });

    it('should return empty array if no files match', async () => {
      const files = await discoverFunctionFiles(tmpDir, 'lib/pingback/**/*.{ts,js}');
      expect(files).toEqual([]);
    });
  });

  describe('generateRouteFile', () => {
    it('should create the route file with correct imports', () => {
      const appDir = join(tmpDir, 'app');
      mkdirSync(appDir, { recursive: true });

      const functionFiles = [
        join(tmpDir, 'lib', 'pingback', 'emails.ts'),
        join(tmpDir, 'lib', 'pingback', 'sync.ts'),
      ];

      generateRouteFile(tmpDir, '/api/__pingback', functionFiles);

      const routePath = join(tmpDir, 'app', 'api', '__pingback', 'route.ts');
      expect(existsSync(routePath)).toBe(true);

      const content = readFileSync(routePath, 'utf-8');
      expect(content).toContain('AUTO-GENERATED BY @usepingback/next');
      expect(content).toContain('import { createRouteHandler } from "@usepingback/next/handler"');
      expect(content).toContain('export const POST = createRouteHandler()');
      expect(content).toContain('lib/pingback/emails');
      expect(content).toContain('lib/pingback/sync');
    });

    it('should handle custom route paths', () => {
      const appDir = join(tmpDir, 'app');
      mkdirSync(appDir, { recursive: true });

      generateRouteFile(tmpDir, '/api/cron', []);

      const routePath = join(tmpDir, 'app', 'api', 'cron', 'route.ts');
      expect(existsSync(routePath)).toBe(true);
    });
  });
});
